### ISSUE TITLE
CI for deploying to server

### ISSUE THREAD

**Issue by avivzk2** [Hamakor/pycon-il-2024#7]
* I can do this easily to but I need credentials to the server/s
* Those I'll save in the variables here on GitHub and use them in GitHub actions to deploy

**Comment by shaib** [comment]
I think it will be easier to use Github Pages. Then we can set the main server to proxy there -- just as we did with Webflow, and just as we are still doing with some of the older years (I'm pretty sure at least 2018 is currently proxied this way)

**Comment by avivzk2** [comment]
Oh got it great

**Comment by shaib** [comment]
Until we set up proper CI for `main` branch, I've set the github pages to deploy static pages when they are pushed to the `/docs` folder in a branch called `manual-github-pages`.

When you work on real CI, feel free to kill this.

**Comment by avivzk2** [comment]
Using GitHub Pages, the CI was just supposed to run the pelican generation command into the /docs folder anytime we merge into main

**Comment by shaib** [comment]
I think it needs to generate into some other place, but anyway, that takes setting up. I think someone defined an action for this.

**Comment by shaib** [comment]
@avivzk2 do you want to take a look at https://docs.getpelican.com/en/latest/tips.html#publishing-to-github-pages ?

**Comment by avivzk2** [comment]
I see you did this already @shaib

**Comment by shaib** [comment]
That's surprising... I didn't. What do you see?

**Comment by shaib** [comment]
Fixed in #20 .
